### ISSUE TITLE
jquery.cycle.lite.js 1.6 is incompatible with jQuery 1.9+

### ISSUE THREAD

**Issue by lck-git** [cmsimple-xh/morepagedata#5]
Mit der [alten Version](https://github.com/cmsimple-xh/morepagedata/blob/master/js/jquery/jquery.cycle.lite.js) (1.6) funktioniert die Slideshow nicht mehr, bitte auf die [neueste Version 1.7](http://malsup.com/jquery/cycle/lite/) updaten.

**Comment by cmb69** [comment]
Danke, Ludwig! Ich habe nun beide Scripts (lite und all) auf die aktuellsten Versionen aktualisiert – beide sind aber doch schon recht betagt (2012 bzw. 2013), so dass es auch in Zukunft wieder Probleme geben könnte.
